CREATE TABLE whereami IF NOT EXISTS (
	id			INTEGER PRIMARY KEY AUTOINCREMENTING,
	lat			REAL,
	lon			REAL,
	alt			REAL,
	timestamp		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	accuracy		REAL DEFAULT 0.0,
	altitude_accuracy	REAL DEFAULT 0.0
);
