name:                whereami
version:             0.1.0.0
github:              "kisom/whereami"
license:             BSD3
author:              "K. Isom"
maintainer:          "kyle@imap.cc"
copyright:           "2018 K. Isom"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Web service allowing me to keep track of my location over time.
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/whereami#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.3.1 && < 1.5
- bytestring >= 0.10 && < 0.11
- scotty >= 0.11.2 && < 1.0
- securemem >= 0.1.1.0 && < 0.2.0
- sqlite-simple >= 0.4.16 && < 0.5
- text >= 1.2 && < 1.3
- unix >= 2.7 && < 3.0
- wai-extra > 3.0 && < 4.0
- warp >= 3.2 && < 3.3

library:
  source-dirs: src

executables:
  whereami-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - whereami

tests:
  whereami-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - whereami
